//! Independent oracle: fixtures generated by the pinned upstream C# code.
use bevy::prelude::*;
use pav_ecs_game_bevy_port::{
    content::map::{parse_map, SpawnKind},
    foundation::fov::FovComputer,
    lighting::{light_to_palette, merge_light, LightContext},
    model::{LightCell, LightKind},
};
use std::collections::HashSet;

fn kind(n: u8) -> LightKind {
    match n {
        0 => LightKind::None,
        1 => LightKind::Fire,
        2 => LightKind::Electricity,
        4 => LightKind::Acid,
        _ => panic!("unknown light kind"),
    }
}

#[test]
fn fov_matches_csharp_on_five_maps_and_shadow_edge_cases() {
    let fixture = include_str!("fixtures/fov_reference.tsv");
    let mut samples = Vec::new();
    let mut sample_index = 0;
    let mut cases = 0;
    let mut case_name = "";
    for line in fixture.lines().filter(|l| !l.starts_with('#')) {
        let fields: Vec<_> = line.split('\t').collect();
        if fields[0] == "case" {
            assert_eq!(
                sample_index,
                samples.len(),
                "incomplete fixture {case_name}"
            );
            case_name = fields[1];
            let origin = IVec2::new(fields[2].parse().unwrap(), fields[3].parse().unwrap());
            let radius = fields[4].parse().unwrap();
            let map = match case_name {
                "map1" => Some(include_str!("../assets/maps/map1.txt")),
                "map2" => Some(include_str!("../assets/maps/map2.txt")),
                "map3" => Some(include_str!("../assets/maps/map3.txt")),
                "map1_test" => Some(include_str!("../assets/maps/map1_test.txt")),
                "lightTest" => Some(include_str!("../assets/maps/lightTest.txt")),
                _ => None,
            };
            let (width, height, walls) = map
                .map(|text| {
                    let (w, h, cells) = parse_map(text);
                    (
                        w,
                        h,
                        cells
                            .into_iter()
                            .filter(|c| c.kind == SpawnKind::Wall)
                            .map(|c| c.pos)
                            .collect::<HashSet<_>>(),
                    )
                })
                .unwrap_or_default();
            // Default is the constructor actually used by Bevy's resource.
            FovComputer::default().compute(
                origin,
                radius,
                |o, d| match case_name {
                    "open" => false,
                    "northwest" => d == IVec2::new(-1, -1),
                    "east" => d == IVec2::X,
                    "ring" => d.x.abs().max(d.y.abs()) == 1,
                    _ => {
                        let p = o + d;
                        p.x < 0 || p.y < 0 || p.x >= width || p.y >= height || walls.contains(&p)
                    }
                },
                &mut samples,
            );
            sample_index = 0;
            cases += 1;
        } else {
            let p = IVec2::new(fields[0].parse().unwrap(), fields[1].parse().unwrap());
            let expected: f32 = fields[2].parse().unwrap();
            let actual = samples[sample_index];
            assert_eq!(actual.delta, p);
            assert!(
                (actual.value - expected).abs() <= 1e-5,
                "{case_name} {p:?}: C# {expected}, Rust {}",
                actual.value
            );
            sample_index += 1;
        }
    }
    assert_eq!(sample_index, samples.len());
    assert_eq!(cases, 9);
}

#[test]
fn light_merge_matches_csharp_for_2880_combinations() {
    let mut count = 0;
    for line in include_str!("fixtures/light_reference.tsv")
        .lines()
        .filter(|l| !l.starts_with('#'))
    {
        let f: Vec<_> = line.split('\t').collect();
        let mut cell = LightCell {
            value: f[0].parse().unwrap(),
            kind: kind(f[1].parse().unwrap()),
        };
        let ctx = LightContext::new(
            (0, 0),
            f[4].parse().unwrap(),
            f[2].parse().unwrap(),
            kind(f[3].parse().unwrap()),
        );
        merge_light(
            &mut cell,
            f[7].parse().unwrap(),
            f[5].parse().unwrap(),
            f[6].parse().unwrap(),
            &ctx,
        );
        assert_eq!(
            cell,
            LightCell {
                value: f[8].parse().unwrap(),
                kind: kind(f[9].parse().unwrap())
            },
            "{line}"
        );
        count += 1;
    }
    assert_eq!(count, 2880);
}

#[test]
fn every_palette_entry_matches_csharp() {
    let mut count = 0;
    for line in include_str!("fixtures/palette_reference.tsv")
        .lines()
        .filter(|l| !l.starts_with('#'))
    {
        let f: Vec<_> = line.split('\t').collect();
        let cell = LightCell {
            kind: kind(f[0].parse().unwrap()),
            value: f[1].parse().unwrap(),
        };
        assert_eq!(
            light_to_palette(&cell),
            f[2].parse::<u8>().unwrap(),
            "{line}"
        );
        count += 1;
    }
    assert_eq!(count, 1024);
}
